server:
  port: 9001

spring:
  application:
    name: eureka-client1

eureka:
  client:
    service-url:
      #defaultZone: http://localhost:8761/eureka/ # one eureka server
      #defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/  # two eureka server
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/ # three eureka server